#!/usr/bin/env python3
"""Adopt main-branch source revisions only after their required CI succeeds."""
import argparse
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile
import tomllib
from urllib.parse import urlencode
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]
TOOLS = ROOT / 'core/tabs/commander'
sys.path.insert(0, str(TOOLS))
from catalog import source_path, validate

SOURCES = {'Myfish': 'Myfish Shell Setup', 'dotfiles': 'Dotfiles'}
BEGIN = '# BEGIN SOURCE CATALOGS (generated by scripts/sync-sources.py)'
END = '# END SOURCE CATALOGS'


def api(path):
    headers = {'Accept': 'application/vnd.github+json', 'X-GitHub-Api-Version': '2022-11-28'}
    if os.environ.get('GH_TOKEN'):
        headers['Authorization'] = 'Bearer ' + os.environ['GH_TOKEN']
    request = Request('https://api.github.com/' + path, headers=headers)
    with urlopen(request, timeout=30) as response:
        return json.load(response)


def eligible_revision(source, request=api):
    repo = f'Commanderx-code/{source}'
    head = request(f'repos/{repo}/commits/main')['sha']
    if not re.fullmatch(r'[0-9a-f]{40}', head):
        raise ValueError('GitHub returned an invalid revision.')
    query = urlencode({'branch': 'main', 'event': 'push', 'head_sha': head, 'per_page': 100})
    runs = request(f'repos/{repo}/actions/workflows/check.yml/runs?{query}')['workflow_runs']
    # Do not filter for success in the API: a newer failed rerun must veto an older success.
    runs = [r for r in runs if r['head_sha'] == head and r['event'] == 'push'
            and r['head_branch'] == 'main' and r['head_repository']['full_name'] == repo]
    latest = max(runs, key=lambda r: (r['id'], r.get('run_attempt', 1)), default=None)
    if latest and latest['status'] == 'completed' and latest['conclusion'] == 'success':
        return head
    print(f'{source}: waiting for successful check.yml on {head[:12]}.')
    return None


def checkout(source, revision, destination):
    subprocess.run(['git', 'init', '-q', str(destination)], check=True)
    subprocess.run(['git', '-C', str(destination), 'fetch', '--quiet', '--depth=1',
                    f'https://github.com/Commanderx-code/{source}.git', revision], check=True)
    subprocess.run(['git', '-C', str(destination), 'checkout', '--quiet', '--detach', 'FETCH_HEAD'], check=True)


def validate_checkout(source, root, document):
    entries = validate(document, source, root)
    # Check the contract of existing consumers as well as new generic exports.
    if source == 'Myfish':
        for path in ('install.sh', 'scripts/bootstrap.py', 'scripts/native.py', 'modules/home.nix'):
            source_path(root, path)
        subprocess.run(['bash', '-n', str(root / 'install.sh')], check=True)
    else:
        required = {
            'dotfiles-nvim': ['configs/nvim/init.lua'],
            'dotfiles-fastfetch': ['configs/fastfetch/config.jsonc', 'configs/fastfetch/png/arch.png'],
            'dotfiles-starship': ['configs/starship/starship.toml'],
            'dotfiles-konsole': ['configs/konsole/Garuda.profile', 'configs/konsole/Sweet.colorscheme'],
            'dotfiles-ghostty': ['configs/ghostty/spotatui.conf'],
            'zellij': [],
        }
        for entry in entries:
            if entry['type'] == 'builtin':
                for path in required[entry['handler']]:
                    source_path(root, path)
        # These integrations consume the same dotfiles pin outside the exported submenu.
        for path in ('configs/topgrade/topgrade.toml', 'sddm/Main.qml', 'sddm/configs/revan.conf'):
            source_path(root, path)


def render(documents):
    chunks, wrappers = [], {}
    names = set()
    for source, menu in SOURCES.items():
        entries = validate(documents[source], source)
        chunks.append(f'[[data]]\nname = {json.dumps(menu)}\n'
                      'description = "Install configurations and tools from the tested source catalog."\n'
                      'multi_select = false\n')
        for entry in entries:
            if entry['name'] in names:
                raise ValueError('Menu names must be unique across source catalogs.')
            names.add(entry['name'])
            if entry['type'] == 'builtin':
                script = f'../commander/{entry["handler"]}.sh'
                if not (TOOLS / f'{entry["handler"]}.sh').is_file():
                    raise ValueError(f'Missing built-in installer: {script}')
            else:
                name = f'{source.lower()}-{entry["id"]}.sh'
                script = f'../commander/generated/{name}'
                wrappers[name] = (f'#!/bin/sh -e\n# Generated from {source}/toolbox.json.\n'
                                  f'cd ..\nexec sh -e ./catalog-install.sh {source} {entry["id"]}\n')
            chunks.append('\n[[data.entries]]\n' + '\n'.join(
                f'{key} = {json.dumps(value)}' for key, value in
                [('name', entry['name']), ('description', entry['description']),
                 ('script', script), ('task_list', 'I FM MP')]) + '\nmulti_select = false\n')
    return '\n'.join(chunks), wrappers


def publish_files(documents, revisions):
    rendered, wrappers = render(documents)
    menu_path = ROOT / 'core/tabs/applications-setup/tab_data.toml'
    original = menu_path.read_text()
    if original.count(BEGIN) != 1 or original.count(END) != 1:
        raise ValueError('Source catalog markers are missing or duplicated.')
    before, rest = original.split(BEGIN)
    _, after = rest.split(END)
    updated = before + BEGIN + '\n' + rendered + '\n' + END + after
    # Catch name collisions with the rest of the application before writing anything.
    generated_names = {e['name'] for d in documents.values() for e in d['entries']}
    all_names = set()
    def walk(entries):
        for entry in entries:
            if 'entries' in entry:
                walk(entry['entries'])
            else:
                if entry['name'] in all_names and entry['name'] in generated_names:
                    raise ValueError(f'Duplicate executable name: {entry["name"]}')
                all_names.add(entry['name'])
    for path in (ROOT / 'core/tabs').glob('*/tab_data.toml'):
        walk(tomllib.loads(updated if path == menu_path else path.read_text())['data'])
    common_path = TOOLS / 'common.sh'
    common = common_path.read_text()
    for source, revision in revisions.items():
        if source not in SOURCES or not re.fullmatch(r'[0-9a-f]{40}', revision):
            raise ValueError('Invalid source pin.')
        common, count = re.subn(rf'({source}\) revision=)[0-9a-f]{{40}}( ;;)',
                                rf'\g<1>{revision}\2', common)
        if count != 1:
            raise ValueError(f'Missing unique source pin: {source}')
    common_path.write_text(common)
    menu_path.write_text(updated)
    for source, document in documents.items():
        (TOOLS / 'catalogs' / f'{source}.json').write_text(json.dumps(document, indent=2) + '\n')
    generated = TOOLS / 'generated'
    generated.mkdir(exist_ok=True)
    for path in generated.glob('*.sh'):
        if path.name not in wrappers:
            path.unlink()
    for name, content in wrappers.items():
        (generated / name).write_text(content)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--render', action='store_true', help='regenerate using embedded catalogs, without network access')
    args = parser.parse_args()
    documents = {source: json.loads((TOOLS / 'catalogs' / f'{source}.json').read_text()) for source in SOURCES}
    revisions = {}
    if not args.render:
        with tempfile.TemporaryDirectory(prefix='toolbox-sync-') as temporary:
            for source in SOURCES:
                revision = eligible_revision(source)
                if revision is None:
                    continue
                destination = Path(temporary) / source
                checkout(source, revision, destination)
                document = json.loads((destination / 'toolbox.json').read_text())
                validate_checkout(source, destination, document)
                documents[source], revisions[source] = document, revision
                print(f'{source}: adopting tested revision {revision}.')
    publish_files(documents, revisions)
    if os.environ.get('GITHUB_OUTPUT'):
        changed = subprocess.check_output(['git', 'status', '--porcelain', '--untracked-files=all'], cwd=ROOT, text=True)
        with open(os.environ['GITHUB_OUTPUT'], 'a') as output:
            output.write(f'changed={str(bool(changed)).lower()}\n')


if __name__ == '__main__':
    main()
